---
- name: install modules required for http checks
  apt: name={{ item }}
  with_items:
    - python-httplib2

- name: create phoenix directory
  file: dest={{ phoenix_distr_prefix }} state=directory

- name: download phoenix
  get_url: url=http://apache-mirror.rbc.ru/pub/apache/phoenix/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}/bin/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin.tar.gz
           dest={{ phoenix_distr_prefix }}/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin.tar.gz
  
- name: unarchive
  unarchive: src={{ phoenix_distr_prefix }}/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin.tar.gz dest={{ phoenix_distr_prefix }} copy=no

- name: create a symlink for phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-server.jar
  file: state=link
        src={{ phoenix_distr_prefix }}/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin/phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-server.jar
        dest={{ hbase_distr_prefix }}-{{ env_name }}-{{ hbase_version }}/lib/phoenix-HBase-server.jar
  register: phoenix_jar
  tags: link

# - file: dest=/opt/hbase/lib/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-server.jar state=absent
#   when: remove is defined
#   tags: remove

- name: create a symlink for hbase-site.xml
  file: state=link
        src=/etc/hbase-{{ env_name }}/hbase-site.xml
        dest={{ phoenix_distr_prefix }}/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin/bin/hbase-site.xml
        force=yes
  tags: config

- name: create a symlink for hbase-policy.xml
  file: state=link
        src=/etc/hbase-{{ env_name }}/hbase-policy.xml
        dest={{ phoenix_distr_prefix }}/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin/bin/hbase-policy.xml
  tags: config

- name: create a symlink for hdfs-site.xml
  file: state=link
        src=/etc/hadoop-{{ env_name }}/hdfs-site.xml
        dest={{ phoenix_distr_prefix }}/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin/bin/hdfs-site.xml
  tags: config

- name: create a symlink for core-site.xml
  file: state=link
        src=/etc/hadoop-{{ env_name }}/core-site.xml
        dest={{ phoenix_distr_prefix }}/apache-phoenix-{{ phoenix_version }}-HBase-{{ phoenix_hbase_version }}-bin/bin/core-site.xml
  tags: config
